### ISSUE TITLE
Latest Release from Jun 14, 2015?

### ISSUE THREAD

**Issue by Isstum** [nzbget/VideoSort#29]
So, maybe you could update this?

**Comment by Kalroth** [comment]
I've made a new release with a bugfix for the guessit implementation here:
https://github.com/Kalroth/VideoSort/releases/tag/v6.2

**Comment by hugbug** [comment]
Current development version includes a big change - upgrade from guessit1 to guessit2. This comes with some issues. A new version of VideoSort will be released when all important issues are fixed.

However since VideoSort doesn't require special installer and the release archive isn't much different from the content of git repository you can always download the latest development version from GitHub via button "Clone or download".

**Comment by hugbug** [comment]
Released v8.0!
