### ISSUE TITLE
Script freezes NAS

### ISSUE THREAD

**Issue by bleedr** [nzbget/VideoSort#39]
Running the script on the Zyxel 325 with Python 2.7 freezes the NAS sometimes. Can be only resolved by removing the file of the movie.

**Comment by hugbug** [comment]
What do you mean with freezing? The system doesn't respond at all? That would indicate rather a hardware issue. Why do you think the freezes are related to the script? Is this reproducible with a certain nzb file?

**Comment by bleedr** [comment]
ie 

ERROR | Sun Apr 22 2018 23:56:03 | Post-process-script VideoSort.py for Dont.Think.Twice.German.AC3.Dubbed.BDRip.x264-PsO failed (terminated with unknown status)
-- | -- | --

**Comment by hugbug** [comment]
Why do you think the freezes are caused by the script? I strongly doubt that the freezes are caused by the script. A python script should not be able to freeze the system.

The error message above shows that the script has been ended (before the system freezes obviously). Any other interesting messages before this one?

**Comment by bleedr** [comment]
Without the script all works fine. Don't think it's a hardware issue.

No, the system log shows that, because I have to switch the NAS off. The script is not terminated by default.

**Comment by hugbug** [comment]
I'm c!owing this because I can't do anything here and I don't think the script is responsible for system freezes.
